#!/usr/bin/env php
<?php

$args = array_slice($argv, 1);
$artisan = __DIR__.DIRECTORY_SEPARATOR.'backend'.DIRECTORY_SEPARATOR.'artisan';
$cmd = 'php '.escapeshellarg($artisan);
foreach ($args as $arg) {
    $cmd .= ' '.escapeshellarg($arg);
}
passthru($cmd, $exitCode);
exit($exitCode);
